### ISSUE TITLE
crud junk station (junk station)

### ISSUE THREAD

**Issue by iqbalpradipta** [capstone-rozhok-app/backend#18]

**Comment by arch-havis** [comment]
- Belum ditambahkan ke factory
- response di samakan di Open API
- tag json kurang tanda petik 2
![Image](https://user-images.githubusercontent.com/110443476/193523442-953df156-2bb6-474f-9602-fe112cd24a1b.png)

- Struct di model jadikan satu sama user saja, contohnya di porter

![Image](https://user-images.githubusercontent.com/110443476/193523746-11a1a06c-b09c-4385-8762-5b421b65fd2a.png)

**Comment by iqbalpradipta** [comment]
Tolong di cek kembali hasil push baru nya .

**Comment by iqbalpradipta** [comment]
untuk factory lupa udah dihubungkan atau belum.
tapi jika belum sudah diubungkan di PR pembelian, thank you !
